%%
%%  !! UPDATE TO YOUR BASE DIR
ImgDir = 'D:\Users\hospelb\labdata\imgproc\imgproc';

% ========================== Image Channels ==========================

run_count = 6;

i = run_count;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\1Day\Tsix'],...
    'imgname', 'mESC_1d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\1Day\Xist'],...
    'imgname', 'mESC_1d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\2Day\Tsix'],...
    'imgname', 'mESC_2d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\2Day\Xist'],...
    'imgname', 'mESC_2d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\3Day\Tsix'],...
    'imgname', 'mESC_3d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\3Day\Xist'],...
    'imgname', 'mESC_3d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
    'tifpath', [ImgDir '\img\mESC\20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
    'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;


% ========================== Common Params ==========================

ctrl_path = [];
ctrl_ch = 0;
ctrl_ch_count = 0;

t_min = 10; 
t_max = 400; 
z_trim = 7;

ttune_winsize = 10;

% ========================== Iterate & Run ==========================

addpath('..');
for i = 1:run_count
    Main_RNASpots(iruns(i).imgname, iruns(i).tifpath, iruns(i).rnach, iruns(i).lightch,...
        iruns(i).ch_count, iruns(i).outdir, t_min, t_max, z_trim, iruns(i).cellseg_path, ctrl_path, ctrl_ch, ctrl_ch_count, ttune_winsize, false);
end
