%%
%%

function rna_spot_run = Main_RNASpots(img_name, tif_path, rna_ch, light_ch, total_ch,...
    out_dir, t_min, t_max, ztrim, cellseg_path, ctrl_path, ctrl_ch, ctrl_chcount, ttune_winsize,...
    ttune_madfactor, overwrite_output)

rna_spot_run = Adapter_RNASpots(img_name, tif_path, rna_ch, light_ch, total_ch,...
    out_dir, t_min, t_max, ztrim, cellseg_path, ctrl_path, ctrl_ch, ctrl_chcount, ttune_winsize,...
    ttune_madfactor, overwrite_output, false);

end